SpaceTeam/STS1_COBC_Docker

linux-x86/Dockerfile
Fixes part of #4
gcc/g++ are handled in #5
=> Specify versions of Ubuntu image and CMake

full/Dockerfile, linux-x86/Dockerfile
Also upgrade the dependencies g++-multilibs and gcc -multlibs, and add a check to ensure that gcc and arm-none-eabi-gcc have the same major version.
Fixes #3 and part of #4
=> Upgrade Arm GNU Toolchain and GCC to version 12

linux-x86/Dockerfile
clangd, clang-format, cmake-format and posh-git-sh
=> Install developer tools

linux-x86/Dockerfile
=>  Add update-alternative call for clangd 

linux-x86/Dockerfile
=> Install Ninja

.github/workflows/ci-tag.yml
=> Fix repository name for dockerhub description

linux-x86/Dockerfile
=> Install vim

linux-x86/Dockerfile
=> Enable tab completion for git

linux-x86/Dockerfile
=> Remove git global config file

linux-x86/Dockerfile
=> Install clang-tidy-cache

full/Dockerfile, linux-x86/Dockerfile
=> Install standalone Experimental Outcome library

full/stm32f411.cmake, linux-x86/Dockerfile
=> Add compile definitions for Experimental Outcome

install.sh, libraries.txt
=> Install NamedType library

install.sh, libraries.txt, linux-x86/Dockerfile
=> Install include-what-you-use

install.sh, libraries.txt
=> Remove type_safe library

libraries.txt
=> Specify version or commit hash for each library

libraries.txt
=> Update Rodos to fix problems with CRC

libraries.txt
=> Update the NamedType library reference in libraries.txt

install.sh
=> Install littlefs also for Linux

linux-x86/Dockerfile
=> Install GDB and Valgrind

install.sh, libraries.txt
=> Build littlefs with LFS_NO_MALLOC

install.sh
=> Revert building littlefs with LFS_NO_MALLOC

install.sh, libraries.txt
Fixes #58 
Also, updates the list of library repositories to be removed, and installs libraries in the order they are listed in libraries.txt.
=> Replace NamedType with strong_type

linux-x86/Dockerfile
=> Install ccache

libraries.txt
=> Update Rodos to enable open drain stuff

install.sh
=> Install debug version of libraries too

linux-x86/Dockerfile
Fixes #80 
For real this time. Hopefully 🙈.
=> Update LLVM APT repository to use version 19

install.sh, libraries.txt
=> Install libfec
